### ISSUE TITLE
Strict dependency breaks shrinkwrap and peerDependency

### ISSUE THREAD

**Issue by artyomtrityak** [JonLim/three-trackballcontrols#10]
Strict peer three.js dependency breaks shrinkwrap and other build processes.

**Comment by dwcaraway** [comment]
I ran `yarn install` for another dependency [react-force-graph](https://github.com/vasturiano/react-force-graph) and ended up with the message below:

> warning "react-force-graph > 3d-force-graph > three-render-objects > three-trackballcon
trols@0.0.7" has incorrect peer dependency "three@^0.86.0"

**Comment by JonLim** [comment]
Please confirm that there's no longer issues with the merging of #9 ? Thanks!

**Comment by dwcaraway** [comment]
I'm still seeing the same warning message.  I don't have a lot of insight on why the warning still occurs -- looks like the peer dependency resolution should be fine. Here's how I tested:

I started by creating a new project `foo`:

```
$ yarn create react-app foo
```

then i cd into the `foo` directory and run:

```bash
$ yarn add three-trackballcontrols
```

this installs `0.0.7` and outputs the warning as expected:

> yarn add v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > three-trackballcontrols@0.0.7" has unmet peer dependency "three@^0.86.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ three-trackballcontrols@0.0.7
info All dependencies
└─ three-trackballcontrols@0.0.7

next,  I remove version `0.0.7` and install from github

```
$ yarn remove three-trackballcontrols
$ yarn add https://github.com/JonLim/three-trackballcontrols.git
```

I see output:
> yarn add v1.7.0
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > three-trackballcontrols@0.0.8" has unmet peer dependency "three@>= 0.86 <= 1.0".
[4/4] Building fresh packages...
success Saved lockfile.
success Saved 1 new dependency.
info Direct dependencies
└─ three-trackballcontrols@0.0.8
info All dependencies
└─ three-trackballcontrols@0.0.8> 

If I continue to force the install, I'll keep getting the warning:

```
$ yarn install --force
```

>Linking dependencies...
warning " > three-trackballcontrols@0.0.8" has unmet peer dependency "three@>= 0.86 <= 1.0".

**Comment by artyomtrityak** [comment]
do you have three as a dependency? Try `yarn add three`

**Comment by dwcaraway** [comment]
@artyomtrityak `yarn add three` gets my test to pass, thanks! question though...I have a transitive dependency to `three-trackballcontrols` starting with [react-force-graph](https://github.com/vasturiano/react-force-graph/blob/master/package.json) .... should one of the intermediate libraries declare the three dependency or should my project, which uses `react-force-graph` declare the `three` dependency?

**Comment by ashl1** [comment]
@dwcaraway If you install only `three-trackballcontrols`, you need to install `three` too. But I've checked `3d-force-graph` has dependency for `three`@0.94.0

@artyomtrityak I suppose 0.0.8 should work. But I think it will be better to use the following restrictions: ">= 0.86 < 1.0" because <= 1.0 includes 1.0 which may break compatibility. Because you haven't published yet, you can do the changes in version 0.0.8 and also publish that.

**Comment by ashl1** [comment]
Sorry, @JonLim you are maintainer. Could you please apply changes and publish 0.0.8? I can test the published changes and confirm resolving this issue.

**Comment by JonLim** [comment]
It looks like this issue has been resolved, or at least nothing has been raised since 2018, so I will be closing this issue.

Let me know if anything else comes up, thanks!
