### ISSUE TITLE
Publish v0.0.6

### ISSUE THREAD

**Issue by vasturiano** [JonLim/three-trackballcontrols#2]
It seems the latest code commit was not published as a new NPM version at https://www.npmjs.com/package/three-trackballcontrols.

Could you please publish the latest version, that includes this fix:
https://github.com/JonLim/three-trackballcontrols/commit/f23ea8c9574640cf5c0c076bccbec96fd32f8091

**Comment by JonLim** [comment]
So sorry on the delay on this, but I've gone ahead and published the new NPM version of `three-trackballcontrolls`.

Included that fix and a few other PRs that were around.

Thanks for taking the time to create this issue!
