### ISSUE TITLE
node_modules presented in npm release

### ISSUE THREAD

**Issue by ashl1** [JonLim/three-trackballcontrols#6]
We use recompact of all `node_modules` with specific transpellers. The installed `three-trackballcontrols` has `node_modules` inside which produce huge impact of code (because it contains three.js inside). We need not to provide `node_modules` dir in builded npm module.

**Comment by ashl1** [comment]
Could you please publish new version without `node_modules`?

**Comment by JonLim** [comment]
Done, sorry about forgetting to do that!
