### ISSUE TITLE
EPSilon should adapt on different absolute distance

### ISSUE THREAD

**Issue by ashl1** [JonLim/three-trackballcontrols#8]
For example, we have the model on micro size (1e-5), the camera rotating with trackballcontrols provide "torn mode", when "change" event is produced too rarely. Because EPS is constant of 1e-6.
But for the big models (like 1e+6) the "change" event will be produced too frequently.
It will be better to use parameter - the coefficient of the "how frequently the Change event will be produced" and the real determination should be by the formula: `lastPosition.distanceToSquared( _this.object.position ) > coeff * EPS * distance_to_target`

**Comment by ashl1** [comment]
Or it might be better to determine the angle between old and new positions with center at `target` and provide only one parameter - `minimumAngle`. When user rotates more than this angle, "change" event should be produced. This is independ on object size or zoom by definition.

**Comment by ashl1** [comment]
Notice: the EPS is used for pan and zoom, not just only for Rotation. In this case, we couldn't use `minimumAngle`, so the best solution is move `EPS` to self arguments to make possible changes from outside.
@JonLim What do you think?

**Comment by JonLim** [comment]
@ashl1 Sorry for the delay in responding.

Did you happen to come up with a solution for your use case? I don't get very much usage out of this library at the moment, so it's difficult for me to reproduce the scenario that you're seeing.

Let me know how I can help.

**Comment by JonLim** [comment]
Closing for now until further activity.
